// What List says, in the 21 languages of the app (Plan §84). English is the source. The plugin's
// name is never written here: it comes from the manifest through the `{app}` hole. Numbers are
// formatted with `Intl` before they fill a hole.

export const STRINGS = {
  en: {
    title: "Lists",
    close: "Close",
    back: "Back",
    newList: "New list",
    namePlaceholder: "Name, e.g. Shopping",
    untitled: "Untitled list",
    empty: "No lists yet",
    progress: "{done} of {total} done",
    shared: "Shared",
    delete: "Delete",
    confirmDelete: "Delete “{name}” from this phone? The other person keeps their copy.",
    cancel: "Cancel",
    rename: "Rename",
    save: "Save",
    addPlaceholder: "Add an item",
    add: "Add",
    edit: "Edit",
    remove: "Remove",
    send: "Put the list in the chat",
    live: "Live",
    stopLive: "Stop live",
    waiting: "🔄 Waiting for the other person…",
    joined: "🔄 Live: you are both on this list",
    silent: "👤 The other person doesn't have {app} open in this conversation. They may not have it, may not have allowed it, or may have it closed.",
    unreachable: "📵 The other phone can't be reached right now.",
    left: "👋 The other person closed the list.",
    outdated: "📦 The other person has a newer {app}. Update {app} to edit together.",
    kept: "Your changes stay on this phone and join theirs when you both have the list open in this conversation.",
    liveHint: "🔄 Live joins your changes only while you both have this list open in this conversation.",
    needsChat: "To edit together, open {app} from a conversation and allow it to go live.",
    localHint: "Lists made here stay on this phone. The lists of a conversation are seen only from that conversation.",
    joinPrompt: "📥 The other person opened “{name}”",
    join: "Join",
    notNow: "Not now",
    received: "Shared list",
    full: "📵 No room left on this phone: the latest changes are not saved. Delete a list to make room.",
    readOnly: "📦 This list comes from a newer {app}: update it to edit.",
  },
  es: {
    title: "Listas",
    close: "Cerrar",
    back: "Atrás",
    newList: "Lista nueva",
    namePlaceholder: "Nombre, p. ej. Compra",
    untitled: "Lista sin nombre",
    empty: "Todavía no hay listas",
    progress: "{done} de {total} hechos",
    shared: "Compartida",
    delete: "Borrar",
    confirmDelete: "¿Borrar «{name}» de este teléfono? La otra persona conserva su copia.",
    cancel: "Cancelar",
    rename: "Renombrar",
    save: "Guardar",
    addPlaceholder: "Añadir un elemento",
    add: "Añadir",
    edit: "Editar",
    remove: "Quitar",
    send: "Poner la lista en el chat",
    live: "En directo",
    stopLive: "Parar el directo",
    waiting: "🔄 Esperando a la otra persona…",
    joined: "🔄 En directo: estáis los dos en esta lista",
    silent: "👤 La otra persona no tiene {app} abierto en esta conversación. Puede que no lo tenga, que no le haya dado permiso o que lo tenga cerrado.",
    unreachable: "📵 Ahora no se puede llegar al otro teléfono.",
    left: "👋 La otra persona cerró la lista.",
    outdated: "📦 La otra persona tiene un {app} más nuevo. Actualiza {app} para editar juntos.",
    kept: "Tus cambios se quedan en este teléfono y se juntan con los suyos cuando los dos tengáis la lista abierta en esta conversación.",
    liveHint: "🔄 El directo junta vuestros cambios solo mientras los dos tengáis esta lista abierta en esta conversación.",
    needsChat: "Para editar juntos, abre {app} desde una conversación, con el directo permitido.",
    localHint: "Las listas hechas aquí se quedan en este teléfono. Las de una conversación solo se ven desde esa conversación.",
    joinPrompt: "📥 La otra persona abrió «{name}»",
    join: "Unirse",
    notNow: "Ahora no",
    received: "Lista compartida",
    full: "📵 No queda sitio en este teléfono: los últimos cambios no se han guardado. Borra una lista para hacer sitio.",
    readOnly: "📦 Esta lista viene de un {app} más nuevo: actualízalo para editarla.",
  },
  fr: {
    title: "Listes",
    close: "Fermer",
    back: "Retour",
    newList: "Nouvelle liste",
    namePlaceholder: "Nom, p. ex. Courses",
    untitled: "Liste sans nom",
    empty: "Aucune liste pour l’instant",
    progress: "{done} sur {total} faits",
    shared: "Partagée",
    delete: "Supprimer",
    confirmDelete: "Supprimer « {name} » de ce téléphone ? L’autre personne garde sa copie.",
    cancel: "Annuler",
    rename: "Renommer",
    save: "Enregistrer",
    addPlaceholder: "Ajouter un élément",
    add: "Ajouter",
    edit: "Modifier",
    remove: "Retirer",
    send: "Mettre la liste dans la discussion",
    live: "En direct",
    stopLive: "Arrêter le direct",
    waiting: "🔄 En attente de l’autre personne…",
    joined: "🔄 En direct : vous êtes tous les deux sur cette liste",
    silent: "👤 L’autre personne n’a pas {app} ouvert dans cette conversation. Elle ne l’a peut-être pas, ne l’a peut-être pas autorisé, ou l’a peut-être fermé.",
    unreachable: "📵 L’autre téléphone est injoignable pour le moment.",
    left: "👋 L’autre personne a fermé la liste.",
    outdated: "📦 L’autre personne a une version plus récente de {app}. Mettez {app} à jour pour modifier ensemble.",
    kept: "Vos modifications restent sur ce téléphone et rejoignent les siennes quand vous avez tous les deux la liste ouverte dans cette conversation.",
    liveHint: "🔄 Le direct réunit vos modifications seulement tant que vous avez tous les deux cette liste ouverte dans cette conversation.",
    needsChat: "Pour modifier ensemble, ouvrez {app} depuis une conversation, avec le direct autorisé.",
    localHint: "Les listes créées ici restent sur ce téléphone. Celles d’une conversation ne se voient que depuis cette conversation.",
    joinPrompt: "📥 L’autre personne a ouvert « {name} »",
    join: "Rejoindre",
    notNow: "Plus tard",
    received: "Liste partagée",
    full: "📵 Plus de place sur ce téléphone : les dernières modifications ne sont pas enregistrées. Supprimez une liste pour faire de la place.",
    readOnly: "📦 Cette liste vient d’une version plus récente de {app} : mettez-le à jour pour la modifier.",
  },
  de: {
    title: "Listen",
    close: "Schließen",
    back: "Zurück",
    newList: "Neue Liste",
    namePlaceholder: "Name, z. B. Einkauf",
    untitled: "Liste ohne Namen",
    empty: "Noch keine Listen",
    progress: "{done} von {total} erledigt",
    shared: "Geteilt",
    delete: "Löschen",
    confirmDelete: "„{name}“ von diesem Telefon löschen? Die andere Person behält ihre Kopie.",
    cancel: "Abbrechen",
    rename: "Umbenennen",
    save: "Speichern",
    addPlaceholder: "Eintrag hinzufügen",
    add: "Hinzufügen",
    edit: "Bearbeiten",
    remove: "Entfernen",
    send: "Liste in den Chat setzen",
    live: "Live",
    stopLive: "Live beenden",
    waiting: "🔄 Warten auf die andere Person…",
    joined: "🔄 Live: Ihr seid beide in dieser Liste",
    silent: "👤 Die andere Person hat {app} in dieser Unterhaltung nicht geöffnet. Vielleicht hat sie es nicht, hat es nicht erlaubt oder hat es geschlossen.",
    unreachable: "📵 Das andere Telefon ist gerade nicht erreichbar.",
    left: "👋 Die andere Person hat die Liste geschlossen.",
    outdated: "📦 Die andere Person hat ein neueres {app}. Aktualisiere {app}, um gemeinsam zu bearbeiten.",
    kept: "Deine Änderungen bleiben auf diesem Telefon und kommen mit ihren zusammen, wenn ihr beide die Liste in dieser Unterhaltung geöffnet habt.",
    liveHint: "🔄 Live führt eure Änderungen nur zusammen, solange ihr beide diese Liste in dieser Unterhaltung geöffnet habt.",
    needsChat: "Um gemeinsam zu bearbeiten, öffne {app} aus einer Unterhaltung, mit erlaubtem Live-Modus.",
    localHint: "Hier erstellte Listen bleiben auf diesem Telefon. Die Listen einer Unterhaltung sieht man nur aus dieser Unterhaltung.",
    joinPrompt: "📥 Die andere Person hat „{name}“ geöffnet",
    join: "Beitreten",
    notNow: "Nicht jetzt",
    received: "Geteilte Liste",
    full: "📵 Kein Platz mehr auf diesem Telefon: Die letzten Änderungen sind nicht gespeichert. Lösche eine Liste, um Platz zu schaffen.",
    readOnly: "📦 Diese Liste stammt aus einem neueren {app}: Aktualisiere es, um sie zu bearbeiten.",
  },
  it: {
    title: "Liste",
    close: "Chiudi",
    back: "Indietro",
    newList: "Nuova lista",
    namePlaceholder: "Nome, es. Spesa",
    untitled: "Lista senza nome",
    empty: "Ancora nessuna lista",
    progress: "{done} di {total} fatti",
    shared: "Condivisa",
    delete: "Elimina",
    confirmDelete: "Eliminare «{name}» da questo telefono? L’altra persona conserva la sua copia.",
    cancel: "Annulla",
    rename: "Rinomina",
    save: "Salva",
    addPlaceholder: "Aggiungi un elemento",
    add: "Aggiungi",
    edit: "Modifica",
    remove: "Rimuovi",
    send: "Metti la lista nella chat",
    live: "In diretta",
    stopLive: "Ferma la diretta",
    waiting: "🔄 In attesa dell’altra persona…",
    joined: "🔄 In diretta: siete entrambi su questa lista",
    silent: "👤 L’altra persona non ha {app} aperto in questa conversazione. Forse non ce l’ha, non l’ha autorizzato o l’ha chiuso.",
    unreachable: "📵 L’altro telefono non è raggiungibile in questo momento.",
    left: "👋 L’altra persona ha chiuso la lista.",
    outdated: "📦 L’altra persona ha una versione più recente di {app}. Aggiorna {app} per modificare insieme.",
    kept: "Le tue modifiche restano su questo telefono e si uniscono alle sue quando avete entrambi la lista aperta in questa conversazione.",
    liveHint: "🔄 La diretta unisce le vostre modifiche solo mentre avete entrambi questa lista aperta in questa conversazione.",
    needsChat: "Per modificare insieme, apri {app} da una conversazione, con la diretta consentita.",
    localHint: "Le liste create qui restano su questo telefono. Quelle di una conversazione si vedono solo da quella conversazione.",
    joinPrompt: "📥 L’altra persona ha aperto «{name}»",
    join: "Unisciti",
    notNow: "Non ora",
    received: "Lista condivisa",
    full: "📵 Non c’è più spazio su questo telefono: le ultime modifiche non sono salvate. Elimina una lista per fare spazio.",
    readOnly: "📦 Questa lista viene da una versione più recente di {app}: aggiornalo per modificarla.",
  },
  pt: {
    title: "Listas",
    close: "Fechar",
    back: "Voltar",
    newList: "Nova lista",
    namePlaceholder: "Nome, p. ex. Compras",
    untitled: "Lista sem nome",
    empty: "Ainda não há listas",
    progress: "{done} de {total} feitos",
    shared: "Partilhada",
    delete: "Apagar",
    confirmDelete: "Apagar «{name}» deste telemóvel? A outra pessoa fica com a sua cópia.",
    cancel: "Cancelar",
    rename: "Mudar o nome",
    save: "Guardar",
    addPlaceholder: "Adicionar um item",
    add: "Adicionar",
    edit: "Editar",
    remove: "Remover",
    send: "Pôr a lista na conversa",
    live: "Em direto",
    stopLive: "Parar o direto",
    waiting: "🔄 À espera da outra pessoa…",
    joined: "🔄 Em direto: estão os dois nesta lista",
    silent: "👤 A outra pessoa não tem o {app} aberto nesta conversa. Pode não o ter, não lhe ter dado permissão ou tê-lo fechado.",
    unreachable: "📵 Agora não é possível chegar ao outro telemóvel.",
    left: "👋 A outra pessoa fechou a lista.",
    outdated: "📦 A outra pessoa tem um {app} mais recente. Atualize o {app} para editarem juntos.",
    kept: "As suas alterações ficam neste telemóvel e juntam-se às da outra pessoa quando os dois tiverem a lista aberta nesta conversa.",
    liveHint: "🔄 O direto junta as vossas alterações só enquanto os dois tiverem esta lista aberta nesta conversa.",
    needsChat: "Para editarem juntos, abra o {app} a partir de uma conversa, com o direto permitido.",
    localHint: "As listas criadas aqui ficam neste telemóvel. As de uma conversa só se veem a partir dessa conversa.",
    joinPrompt: "📥 A outra pessoa abriu «{name}»",
    join: "Entrar",
    notNow: "Agora não",
    received: "Lista partilhada",
    full: "📵 Não há espaço neste telemóvel: as últimas alterações não foram guardadas. Apague uma lista para libertar espaço.",
    readOnly: "📦 Esta lista vem de um {app} mais recente: atualize-o para a editar.",
  },
  ro: {
    title: "Liste",
    close: "Închide",
    back: "Înapoi",
    newList: "Listă nouă",
    namePlaceholder: "Nume, de ex. Cumpărături",
    untitled: "Listă fără nume",
    empty: "Încă nu există liste",
    progress: "{done} din {total} gata",
    shared: "Partajată",
    delete: "Șterge",
    confirmDelete: "Ștergi „{name}” de pe acest telefon? Cealaltă persoană își păstrează copia.",
    cancel: "Anulează",
    rename: "Redenumește",
    save: "Salvează",
    addPlaceholder: "Adaugă un element",
    add: "Adaugă",
    edit: "Editează",
    remove: "Elimină",
    send: "Pune lista în conversație",
    live: "În direct",
    stopLive: "Oprește modul în direct",
    waiting: "🔄 Se așteaptă cealaltă persoană…",
    joined: "🔄 În direct: sunteți amândoi pe această listă",
    silent: "👤 Cealaltă persoană nu are {app} deschis în această conversație. Poate nu îl are, nu i-a dat permisiunea sau l-a închis.",
    unreachable: "📵 Celălalt telefon nu poate fi contactat acum.",
    left: "👋 Cealaltă persoană a închis lista.",
    outdated: "📦 Cealaltă persoană are o versiune mai nouă de {app}. Actualizează {app} ca să editați împreună.",
    kept: "Modificările tale rămân pe acest telefon și se unesc cu ale ei când aveți amândoi lista deschisă în această conversație.",
    liveHint: "🔄 Modul în direct vă unește modificările doar cât timp aveți amândoi această listă deschisă în această conversație.",
    needsChat: "Ca să editați împreună, deschide {app} dintr-o conversație, cu modul în direct permis.",
    localHint: "Listele făcute aici rămân pe acest telefon. Listele unei conversații se văd doar din acea conversație.",
    joinPrompt: "📥 Cealaltă persoană a deschis „{name}”",
    join: "Alătură-te",
    notNow: "Nu acum",
    received: "Listă partajată",
    full: "📵 Nu mai e loc pe acest telefon: ultimele modificări nu sunt salvate. Șterge o listă ca să faci loc.",
    readOnly: "📦 Această listă vine dintr-o versiune mai nouă de {app}: actualizează-l ca s-o editezi.",
  },
  pl: {
    title: "Listy",
    close: "Zamknij",
    back: "Wstecz",
    newList: "Nowa lista",
    namePlaceholder: "Nazwa, np. Zakupy",
    untitled: "Lista bez nazwy",
    empty: "Nie ma jeszcze list",
    progress: "Zrobione: {done} z {total}",
    shared: "Udostępniona",
    delete: "Usuń",
    confirmDelete: "Usunąć „{name}” z tego telefonu? Druga osoba zachowa swoją kopię.",
    cancel: "Anuluj",
    rename: "Zmień nazwę",
    save: "Zapisz",
    addPlaceholder: "Dodaj pozycję",
    add: "Dodaj",
    edit: "Edytuj",
    remove: "Usuń pozycję",
    send: "Wstaw listę do czatu",
    live: "Na żywo",
    stopLive: "Zakończ tryb na żywo",
    waiting: "🔄 Czekanie na drugą osobę…",
    joined: "🔄 Na żywo: oboje jesteście na tej liście",
    silent: "👤 Druga osoba nie ma otwartej aplikacji {app} w tej rozmowie. Może jej nie mieć, mogła nie dać zgody albo ją zamknęła.",
    unreachable: "📵 Nie można teraz połączyć się z drugim telefonem.",
    left: "👋 Druga osoba zamknęła listę.",
    outdated: "📦 Druga osoba ma nowszą wersję {app}. Zaktualizuj {app}, aby edytować razem.",
    kept: "Twoje zmiany zostają na tym telefonie i połączą się z jej zmianami, gdy oboje będziecie mieć listę otwartą w tej rozmowie.",
    liveHint: "🔄 Tryb na żywo łączy wasze zmiany tylko wtedy, gdy oboje macie tę listę otwartą w tej rozmowie.",
    needsChat: "Aby edytować razem, otwórz {app} z rozmowy, z dozwolonym trybem na żywo.",
    localHint: "Listy utworzone tutaj zostają na tym telefonie. Listy rozmowy widać tylko z tej rozmowy.",
    joinPrompt: "📥 Druga osoba otworzyła „{name}”",
    join: "Dołącz",
    notNow: "Nie teraz",
    received: "Udostępniona lista",
    full: "📵 Brak miejsca na tym telefonie: ostatnie zmiany nie są zapisane. Usuń listę, aby zrobić miejsce.",
    readOnly: "📦 Ta lista pochodzi z nowszej wersji {app}: zaktualizuj ją, aby edytować.",
  },
  ru: {
    title: "Списки",
    close: "Закрыть",
    back: "Назад",
    newList: "Новый список",
    namePlaceholder: "Название, напр. Покупки",
    untitled: "Список без названия",
    empty: "Списков пока нет",
    progress: "Готово {done} из {total}",
    shared: "Общий",
    delete: "Удалить",
    confirmDelete: "Удалить «{name}» с этого телефона? У другого человека останется его копия.",
    cancel: "Отмена",
    rename: "Переименовать",
    save: "Сохранить",
    addPlaceholder: "Добавить пункт",
    add: "Добавить",
    edit: "Изменить",
    remove: "Убрать",
    send: "Вставить список в чат",
    live: "Вместе",
    stopLive: "Закончить совместную работу",
    waiting: "🔄 Ждём другого человека…",
    joined: "🔄 Вместе: вы оба в этом списке",
    silent: "👤 У другого человека не открыт {app} в этой переписке. Возможно, у него его нет, он не дал разрешение или закрыл его.",
    unreachable: "📵 Сейчас до другого телефона не достучаться.",
    left: "👋 Другой человек закрыл список.",
    outdated: "📦 У другого человека более новая версия {app}. Обновите {app}, чтобы редактировать вместе.",
    kept: "Ваши изменения остаются на этом телефоне и объединятся с его изменениями, когда у вас обоих будет открыт список в этой переписке.",
    liveHint: "🔄 Изменения объединяются, только пока у вас обоих открыт этот список в этой переписке.",
    needsChat: "Чтобы редактировать вместе, откройте {app} из переписки и разрешите ему совместную работу.",
    localHint: "Списки, созданные здесь, остаются на этом телефоне. Списки переписки видны только из этой переписки.",
    joinPrompt: "📥 Другой человек открыл «{name}»",
    join: "Присоединиться",
    notNow: "Не сейчас",
    received: "Общий список",
    full: "📵 На этом телефоне не осталось места: последние изменения не сохранены. Удалите список, чтобы освободить место.",
    readOnly: "📦 Этот список из более новой версии {app}: обновите его, чтобы редактировать.",
  },
  uk: {
    title: "Списки",
    close: "Закрити",
    back: "Назад",
    newList: "Новий список",
    namePlaceholder: "Назва, напр. Покупки",
    untitled: "Список без назви",
    empty: "Списків поки немає",
    progress: "Готово {done} з {total}",
    shared: "Спільний",
    delete: "Видалити",
    confirmDelete: "Видалити «{name}» з цього телефона? Інша людина збереже свою копію.",
    cancel: "Скасувати",
    rename: "Перейменувати",
    save: "Зберегти",
    addPlaceholder: "Додати пункт",
    add: "Додати",
    edit: "Змінити",
    remove: "Прибрати",
    send: "Вставити список у чат",
    live: "Разом",
    stopLive: "Завершити спільну роботу",
    waiting: "🔄 Чекаємо на іншу людину…",
    joined: "🔄 Разом: ви обоє в цьому списку",
    silent: "👤 Інша людина не має відкритого {app} у цій розмові. Можливо, у неї його немає, вона не дала дозволу або закрила його.",
    unreachable: "📵 Зараз до іншого телефона не можна достукатися.",
    left: "👋 Інша людина закрила список.",
    outdated: "📦 Інша людина має новішу версію {app}. Оновіть {app}, щоб редагувати разом.",
    kept: "Ваші зміни залишаються на цьому телефоні й об’єднаються з її змінами, коли у вас обох буде відкритий список у цій розмові.",
    liveHint: "🔄 Зміни об’єднуються, лише поки у вас обох відкритий цей список у цій розмові.",
    needsChat: "Щоб редагувати разом, відкрийте {app} з розмови й дозвольте йому спільну роботу.",
    localHint: "Списки, створені тут, залишаються на цьому телефоні. Списки розмови видно лише з цієї розмови.",
    joinPrompt: "📥 Інша людина відкрила «{name}»",
    join: "Приєднатися",
    notNow: "Не зараз",
    received: "Спільний список",
    full: "📵 На цьому телефоні не залишилося місця: останні зміни не збережено. Видаліть список, щоб звільнити місце.",
    readOnly: "📦 Цей список із новішої версії {app}: оновіть його, щоб редагувати.",
  },
  tr: {
    title: "Listeler",
    close: "Kapat",
    back: "Geri",
    newList: "Yeni liste",
    namePlaceholder: "Ad, ör. Alışveriş",
    untitled: "Adsız liste",
    empty: "Henüz liste yok",
    progress: "{total} öğeden {done} tanesi tamam",
    shared: "Paylaşılan",
    delete: "Sil",
    confirmDelete: "“{name}” bu telefondan silinsin mi? Diğer kişi kendi kopyasını tutar.",
    cancel: "İptal",
    rename: "Yeniden adlandır",
    save: "Kaydet",
    addPlaceholder: "Öğe ekle",
    add: "Ekle",
    edit: "Düzenle",
    remove: "Kaldır",
    send: "Listeyi sohbete koy",
    live: "Canlı",
    stopLive: "Canlıyı durdur",
    waiting: "🔄 Diğer kişi bekleniyor…",
    joined: "🔄 Canlı: ikiniz de bu listedesiniz",
    silent: "👤 Diğer kişide bu sohbette {app} açık değil. Onda olmayabilir, izin vermemiş olabilir ya da kapatmış olabilir.",
    unreachable: "📵 Diğer telefona şu anda ulaşılamıyor.",
    left: "👋 Diğer kişi listeyi kapattı.",
    outdated: "📦 Diğer kişide daha yeni bir {app} var. Birlikte düzenlemek için {app} uygulamasını güncelleyin.",
    kept: "Değişiklikleriniz bu telefonda kalır ve ikiniz de listeyi bu sohbette açtığınızda onunkilerle birleşir.",
    liveHint: "🔄 Canlı mod değişikliklerinizi yalnızca ikiniz de bu listeyi bu sohbette açık tuttuğunuz sürece birleştirir.",
    needsChat: "Birlikte düzenlemek için {app} uygulamasını bir sohbetten açın ve canlı moda izin verin.",
    localHint: "Burada oluşturulan listeler bu telefonda kalır. Bir sohbetin listeleri yalnızca o sohbetten görülür.",
    joinPrompt: "📥 Diğer kişi “{name}” listesini açtı",
    join: "Katıl",
    notNow: "Şimdi değil",
    received: "Paylaşılan liste",
    full: "📵 Bu telefonda yer kalmadı: son değişiklikler kaydedilmedi. Yer açmak için bir liste silin.",
    readOnly: "📦 Bu liste daha yeni bir {app} sürümünden geliyor: düzenlemek için güncelleyin.",
  },
  ar: {
    title: "القوائم",
    close: "إغلاق",
    back: "رجوع",
    newList: "قائمة جديدة",
    namePlaceholder: "الاسم، مثلًا: مشتريات",
    untitled: "قائمة بلا اسم",
    empty: "لا توجد قوائم بعد",
    progress: "تم {done} من {total}",
    shared: "مشتركة",
    delete: "حذف",
    confirmDelete: "هل تحذف «{name}» من هذا الهاتف؟ يحتفظ الشخص الآخر بنسخته.",
    cancel: "إلغاء",
    rename: "إعادة التسمية",
    save: "حفظ",
    addPlaceholder: "أضف عنصرًا",
    add: "إضافة",
    edit: "تعديل",
    remove: "إزالة",
    send: "ضع القائمة في المحادثة",
    live: "مباشر",
    stopLive: "إيقاف المباشر",
    waiting: "🔄 بانتظار الشخص الآخر…",
    joined: "🔄 مباشر: أنتما الاثنان في هذه القائمة",
    silent: "👤 ليس لدى الشخص الآخر {app} مفتوحًا في هذه المحادثة. ربما لا يملكه، أو لم يمنحه الإذن، أو أغلقه.",
    unreachable: "📵 لا يمكن الوصول إلى الهاتف الآخر الآن.",
    left: "👋 أغلق الشخص الآخر القائمة.",
    outdated: "📦 لدى الشخص الآخر إصدار أحدث من {app}. حدّث {app} لتعدّلا معًا.",
    kept: "تبقى تغييراتك على هذا الهاتف وتنضم إلى تغييراته عندما تكون القائمة مفتوحة لديكما في هذه المحادثة.",
    liveHint: "🔄 يجمع الوضع المباشر تغييراتكما فقط ما دامت هذه القائمة مفتوحة لديكما في هذه المحادثة.",
    needsChat: "للتعديل معًا، افتح {app} من محادثة مع السماح له بالوضع المباشر.",
    localHint: "تبقى القوائم المنشأة هنا على هذا الهاتف. لا تظهر قوائم المحادثة إلا من داخل تلك المحادثة.",
    joinPrompt: "📥 فتح الشخص الآخر «{name}»",
    join: "انضمام",
    notNow: "ليس الآن",
    received: "قائمة مشتركة",
    full: "📵 لا توجد مساحة كافية على هذا الهاتف: لم تُحفظ آخر التغييرات. احذف قائمة لإفساح المجال.",
    readOnly: "📦 هذه القائمة من إصدار أحدث من {app}: حدّثه لتعديلها.",
  },
  hi: {
    title: "सूचियाँ",
    close: "बंद करें",
    back: "वापस",
    newList: "नई सूची",
    namePlaceholder: "नाम, जैसे खरीदारी",
    untitled: "बिना नाम की सूची",
    empty: "अभी कोई सूची नहीं",
    progress: "{total} में से {done} हो गए",
    shared: "साझा",
    delete: "मिटाएँ",
    confirmDelete: "“{name}” इस फ़ोन से मिटाएँ? दूसरे व्यक्ति के पास उसकी कॉपी रहेगी।",
    cancel: "रद्द करें",
    rename: "नाम बदलें",
    save: "सहेजें",
    addPlaceholder: "कोई आइटम जोड़ें",
    add: "जोड़ें",
    edit: "बदलें",
    remove: "हटाएँ",
    send: "सूची चैट में रखें",
    live: "लाइव",
    stopLive: "लाइव बंद करें",
    waiting: "🔄 दूसरे व्यक्ति का इंतज़ार…",
    joined: "🔄 लाइव: आप दोनों इस सूची में हैं",
    silent: "👤 दूसरे व्यक्ति के पास इस बातचीत में {app} खुला नहीं है। हो सकता है उनके पास यह न हो, उन्होंने अनुमति न दी हो, या इसे बंद कर दिया हो।",
    unreachable: "📵 अभी दूसरे फ़ोन तक नहीं पहुँचा जा सकता।",
    left: "👋 दूसरे व्यक्ति ने सूची बंद कर दी।",
    outdated: "📦 दूसरे व्यक्ति के पास {app} का नया संस्करण है। साथ में बदलने के लिए {app} अपडेट करें।",
    kept: "आपके बदलाव इस फ़ोन पर रहते हैं और जब आप दोनों इस बातचीत में सूची खोलेंगे, तब उनके बदलावों से मिल जाएँगे।",
    liveHint: "🔄 लाइव आपके बदलाव तभी मिलाता है जब आप दोनों ने इस बातचीत में यह सूची खोल रखी हो।",
    needsChat: "साथ में बदलने के लिए {app} को किसी बातचीत से खोलें और उसे लाइव की अनुमति दें।",
    localHint: "यहाँ बनी सूचियाँ इसी फ़ोन पर रहती हैं। किसी बातचीत की सूचियाँ सिर्फ़ उसी बातचीत से दिखती हैं।",
    joinPrompt: "📥 दूसरे व्यक्ति ने “{name}” खोली",
    join: "जुड़ें",
    notNow: "अभी नहीं",
    received: "साझा सूची",
    full: "📵 इस फ़ोन पर जगह नहीं बची: आख़िरी बदलाव सहेजे नहीं गए। जगह बनाने के लिए कोई सूची मिटाएँ।",
    readOnly: "📦 यह सूची {app} के नए संस्करण से है: इसे बदलने के लिए अपडेट करें।",
  },
  bn: {
    title: "তালিকা",
    close: "বন্ধ",
    back: "পিছনে",
    newList: "নতুন তালিকা",
    namePlaceholder: "নাম, যেমন কেনাকাটা",
    untitled: "নামহীন তালিকা",
    empty: "এখনও কোনো তালিকা নেই",
    progress: "{total}টির মধ্যে {done}টি হয়েছে",
    shared: "শেয়ার করা",
    delete: "মুছুন",
    confirmDelete: "“{name}” এই ফোন থেকে মুছবেন? অন্যজনের কাছে তার কপি থাকবে।",
    cancel: "বাতিল",
    rename: "নাম বদলান",
    save: "সংরক্ষণ",
    addPlaceholder: "একটি আইটেম যোগ করুন",
    add: "যোগ করুন",
    edit: "সম্পাদনা",
    remove: "সরান",
    send: "তালিকাটি চ্যাটে রাখুন",
    live: "লাইভ",
    stopLive: "লাইভ বন্ধ করুন",
    waiting: "🔄 অন্যজনের জন্য অপেক্ষা…",
    joined: "🔄 লাইভ: আপনারা দুজনেই এই তালিকায় আছেন",
    silent: "👤 অন্যজনের এই কথোপকথনে {app} খোলা নেই। হয়তো তার কাছে এটি নেই, অনুমতি দেননি, বা বন্ধ করে রেখেছেন।",
    unreachable: "📵 এখন অন্য ফোনে পৌঁছানো যাচ্ছে না।",
    left: "👋 অন্যজন তালিকাটি বন্ধ করেছেন।",
    outdated: "📦 অন্যজনের কাছে {app}-এর নতুন সংস্করণ আছে। একসাথে সম্পাদনা করতে {app} আপডেট করুন।",
    kept: "আপনার পরিবর্তন এই ফোনে থাকে এবং আপনারা দুজনেই এই কথোপকথনে তালিকাটি খুললে তার পরিবর্তনের সাথে মিলে যায়।",
    liveHint: "🔄 লাইভ আপনাদের পরিবর্তন শুধু তখনই মেলায় যখন দুজনেই এই কথোপকথনে তালিকাটি খুলে রাখেন।",
    needsChat: "একসাথে সম্পাদনা করতে কোনো কথোপকথন থেকে {app} খুলুন এবং লাইভের অনুমতি দিন।",
    localHint: "এখানে তৈরি তালিকা এই ফোনেই থাকে। কোনো কথোপকথনের তালিকা শুধু সেই কথোপকথন থেকেই দেখা যায়।",
    joinPrompt: "📥 অন্যজন “{name}” খুলেছেন",
    join: "যোগ দিন",
    notNow: "এখন নয়",
    received: "শেয়ার করা তালিকা",
    full: "📵 এই ফোনে আর জায়গা নেই: শেষ পরিবর্তনগুলো সংরক্ষিত হয়নি। জায়গা করতে একটি তালিকা মুছুন।",
    readOnly: "📦 এই তালিকাটি {app}-এর নতুন সংস্করণ থেকে এসেছে: সম্পাদনা করতে আপডেট করুন।",
  },
  id: {
    title: "Daftar",
    close: "Tutup",
    back: "Kembali",
    newList: "Daftar baru",
    namePlaceholder: "Nama, mis. Belanja",
    untitled: "Daftar tanpa nama",
    empty: "Belum ada daftar",
    progress: "{done} dari {total} selesai",
    shared: "Dibagikan",
    delete: "Hapus",
    confirmDelete: "Hapus “{name}” dari ponsel ini? Orang lain tetap menyimpan salinannya.",
    cancel: "Batal",
    rename: "Ganti nama",
    save: "Simpan",
    addPlaceholder: "Tambah item",
    add: "Tambah",
    edit: "Ubah",
    remove: "Buang",
    send: "Taruh daftar di obrolan",
    live: "Langsung",
    stopLive: "Hentikan mode langsung",
    waiting: "🔄 Menunggu orang lain…",
    joined: "🔄 Langsung: kalian berdua ada di daftar ini",
    silent: "👤 Orang lain tidak membuka {app} di percakapan ini. Mungkin dia tidak memilikinya, tidak memberi izin, atau sudah menutupnya.",
    unreachable: "📵 Ponsel lain tidak dapat dijangkau sekarang.",
    left: "👋 Orang lain menutup daftar.",
    outdated: "📦 Orang lain punya {app} versi lebih baru. Perbarui {app} untuk mengedit bersama.",
    kept: "Perubahan Anda tetap di ponsel ini dan bergabung dengan perubahannya saat kalian berdua membuka daftar di percakapan ini.",
    liveHint: "🔄 Mode langsung menggabungkan perubahan kalian hanya selama kalian berdua membuka daftar ini di percakapan ini.",
    needsChat: "Untuk mengedit bersama, buka {app} dari sebuah percakapan dan izinkan mode langsung.",
    localHint: "Daftar yang dibuat di sini tetap di ponsel ini. Daftar sebuah percakapan hanya terlihat dari percakapan itu.",
    joinPrompt: "📥 Orang lain membuka “{name}”",
    join: "Gabung",
    notNow: "Nanti",
    received: "Daftar bersama",
    full: "📵 Ruang di ponsel ini habis: perubahan terakhir belum tersimpan. Hapus sebuah daftar untuk memberi ruang.",
    readOnly: "📦 Daftar ini berasal dari {app} versi lebih baru: perbarui untuk mengeditnya.",
  },
  vi: {
    title: "Danh sách",
    close: "Đóng",
    back: "Quay lại",
    newList: "Danh sách mới",
    namePlaceholder: "Tên, ví dụ: Đi chợ",
    untitled: "Danh sách chưa đặt tên",
    empty: "Chưa có danh sách nào",
    progress: "Đã xong {done}/{total}",
    shared: "Đã chia sẻ",
    delete: "Xóa",
    confirmDelete: "Xóa “{name}” khỏi điện thoại này? Người kia vẫn giữ bản của họ.",
    cancel: "Hủy",
    rename: "Đổi tên",
    save: "Lưu",
    addPlaceholder: "Thêm một mục",
    add: "Thêm",
    edit: "Sửa",
    remove: "Bỏ",
    send: "Đưa danh sách vào cuộc trò chuyện",
    live: "Trực tiếp",
    stopLive: "Dừng trực tiếp",
    waiting: "🔄 Đang chờ người kia…",
    joined: "🔄 Trực tiếp: cả hai đang ở danh sách này",
    silent: "👤 Người kia chưa mở {app} trong cuộc trò chuyện này. Có thể họ không có, chưa cho phép, hoặc đã đóng nó.",
    unreachable: "📵 Hiện không liên lạc được với điện thoại kia.",
    left: "👋 Người kia đã đóng danh sách.",
    outdated: "📦 Người kia có {app} mới hơn. Hãy cập nhật {app} để cùng chỉnh sửa.",
    kept: "Thay đổi của bạn vẫn ở trên điện thoại này và sẽ gộp với của họ khi cả hai cùng mở danh sách trong cuộc trò chuyện này.",
    liveHint: "🔄 Chế độ trực tiếp chỉ gộp thay đổi khi cả hai đang mở danh sách này trong cuộc trò chuyện này.",
    needsChat: "Để cùng chỉnh sửa, hãy mở {app} từ một cuộc trò chuyện và cho phép chế độ trực tiếp.",
    localHint: "Danh sách tạo ở đây chỉ ở trên điện thoại này. Danh sách của một cuộc trò chuyện chỉ xem được từ cuộc trò chuyện đó.",
    joinPrompt: "📥 Người kia đã mở “{name}”",
    join: "Tham gia",
    notNow: "Để sau",
    received: "Danh sách được chia sẻ",
    full: "📵 Điện thoại này hết chỗ: các thay đổi mới nhất chưa được lưu. Hãy xóa một danh sách để có chỗ.",
    readOnly: "📦 Danh sách này đến từ {app} mới hơn: hãy cập nhật để chỉnh sửa.",
  },
  th: {
    title: "รายการ",
    close: "ปิด",
    back: "กลับ",
    newList: "รายการใหม่",
    namePlaceholder: "ชื่อ เช่น ซื้อของ",
    untitled: "รายการไม่มีชื่อ",
    empty: "ยังไม่มีรายการ",
    progress: "เสร็จ {done} จาก {total}",
    shared: "แชร์แล้ว",
    delete: "ลบ",
    confirmDelete: "ลบ “{name}” ออกจากโทรศัพท์นี้ไหม อีกฝ่ายยังมีสำเนาของตัวเอง",
    cancel: "ยกเลิก",
    rename: "เปลี่ยนชื่อ",
    save: "บันทึก",
    addPlaceholder: "เพิ่มรายการย่อย",
    add: "เพิ่ม",
    edit: "แก้ไข",
    remove: "เอาออก",
    send: "ใส่รายการลงในแชท",
    live: "เรียลไทม์",
    stopLive: "หยุดเรียลไทม์",
    waiting: "🔄 กำลังรออีกฝ่าย…",
    joined: "🔄 เรียลไทม์: คุณทั้งสองอยู่ในรายการนี้",
    silent: "👤 อีกฝ่ายไม่ได้เปิด {app} ในการสนทนานี้ อาจไม่มีแอปนี้ ไม่ได้อนุญาต หรือปิดไปแล้ว",
    unreachable: "📵 ตอนนี้ติดต่อโทรศัพท์อีกเครื่องไม่ได้",
    left: "👋 อีกฝ่ายปิดรายการแล้ว",
    outdated: "📦 อีกฝ่ายมี {app} เวอร์ชันใหม่กว่า อัปเดต {app} เพื่อแก้ไขด้วยกัน",
    kept: "การเปลี่ยนแปลงของคุณอยู่ในโทรศัพท์นี้ และจะรวมกับของอีกฝ่ายเมื่อทั้งสองเปิดรายการในการสนทนานี้",
    liveHint: "🔄 โหมดเรียลไทม์รวมการเปลี่ยนแปลงเฉพาะตอนที่ทั้งสองเปิดรายการนี้ในการสนทนานี้",
    needsChat: "หากต้องการแก้ไขด้วยกัน ให้เปิด {app} จากการสนทนาและอนุญาตโหมดเรียลไทม์",
    localHint: "รายการที่สร้างที่นี่อยู่ในโทรศัพท์นี้เท่านั้น รายการของการสนทนาจะเห็นได้จากการสนทนานั้นเท่านั้น",
    joinPrompt: "📥 อีกฝ่ายเปิด “{name}”",
    join: "เข้าร่วม",
    notNow: "ไว้ทีหลัง",
    received: "รายการที่แชร์",
    full: "📵 โทรศัพท์นี้ไม่มีที่ว่างแล้ว: การเปลี่ยนแปลงล่าสุดยังไม่ได้บันทึก ลบรายการหนึ่งเพื่อเพิ่มที่ว่าง",
    readOnly: "📦 รายการนี้มาจาก {app} เวอร์ชันใหม่กว่า: อัปเดตเพื่อแก้ไข",
  },
  ja: {
    title: "リスト",
    close: "閉じる",
    back: "戻る",
    newList: "新しいリスト",
    namePlaceholder: "名前（例：買い物）",
    untitled: "名前のないリスト",
    empty: "リストはまだありません",
    progress: "{total} 件中 {done} 件完了",
    shared: "共有中",
    delete: "削除",
    confirmDelete: "「{name}」をこの電話から削除しますか？相手のコピーは残ります。",
    cancel: "キャンセル",
    rename: "名前を変更",
    save: "保存",
    addPlaceholder: "項目を追加",
    add: "追加",
    edit: "編集",
    remove: "削除する",
    send: "リストをチャットに入れる",
    live: "ライブ",
    stopLive: "ライブを終了",
    waiting: "🔄 相手を待っています…",
    joined: "🔄 ライブ：二人ともこのリストにいます",
    silent: "👤 相手はこの会話で {app} を開いていません。持っていない、許可していない、または閉じている可能性があります。",
    unreachable: "📵 今は相手の電話に届きません。",
    left: "👋 相手がリストを閉じました。",
    outdated: "📦 相手の {app} のほうが新しいバージョンです。一緒に編集するには {app} を更新してください。",
    kept: "あなたの変更はこの電話に残り、二人ともこの会話でリストを開いたときに相手の変更とまとまります。",
    liveHint: "🔄 ライブで変更がまとまるのは、二人ともこの会話でこのリストを開いている間だけです。",
    needsChat: "一緒に編集するには、会話から {app} を開き、ライブを許可してください。",
    localHint: "ここで作ったリストはこの電話にだけ残ります。会話のリストはその会話からしか見えません。",
    joinPrompt: "📥 相手が「{name}」を開きました",
    join: "参加",
    notNow: "今はしない",
    received: "共有リスト",
    full: "📵 この電話に空きがありません：最新の変更は保存されていません。リストを削除して空きを作ってください。",
    readOnly: "📦 このリストは新しいバージョンの {app} で作られています：編集するには更新してください。",
  },
  ko: {
    title: "목록",
    close: "닫기",
    back: "뒤로",
    newList: "새 목록",
    namePlaceholder: "이름 (예: 장보기)",
    untitled: "이름 없는 목록",
    empty: "아직 목록이 없습니다",
    progress: "{total}개 중 {done}개 완료",
    shared: "공유됨",
    delete: "삭제",
    confirmDelete: "“{name}”을(를) 이 휴대폰에서 삭제할까요? 상대방은 자신의 사본을 그대로 가집니다.",
    cancel: "취소",
    rename: "이름 바꾸기",
    save: "저장",
    addPlaceholder: "항목 추가",
    add: "추가",
    edit: "수정",
    remove: "빼기",
    send: "목록을 채팅에 넣기",
    live: "실시간",
    stopLive: "실시간 끝내기",
    waiting: "🔄 상대방을 기다리는 중…",
    joined: "🔄 실시간: 두 사람 모두 이 목록에 있습니다",
    silent: "👤 상대방이 이 대화에서 {app}을(를) 열지 않았습니다. 앱이 없거나, 허용하지 않았거나, 닫았을 수 있습니다.",
    unreachable: "📵 지금은 상대방 휴대폰에 연결할 수 없습니다.",
    left: "👋 상대방이 목록을 닫았습니다.",
    outdated: "📦 상대방의 {app}이(가) 더 새 버전입니다. 함께 수정하려면 {app}을(를) 업데이트하세요.",
    kept: "변경 내용은 이 휴대폰에 남아 있다가, 두 사람 모두 이 대화에서 목록을 열면 상대방의 변경 내용과 합쳐집니다.",
    liveHint: "🔄 실시간 모드는 두 사람 모두 이 대화에서 이 목록을 열어 둔 동안에만 변경 내용을 합칩니다.",
    needsChat: "함께 수정하려면 대화에서 {app}을(를) 열고 실시간을 허용하세요.",
    localHint: "여기서 만든 목록은 이 휴대폰에만 남습니다. 대화의 목록은 그 대화에서만 보입니다.",
    joinPrompt: "📥 상대방이 “{name}”을(를) 열었습니다",
    join: "참여",
    notNow: "나중에",
    received: "공유된 목록",
    full: "📵 이 휴대폰에 공간이 없습니다: 최근 변경 내용이 저장되지 않았습니다. 목록을 삭제해 공간을 만드세요.",
    readOnly: "📦 이 목록은 더 새 버전의 {app}에서 왔습니다: 수정하려면 업데이트하세요.",
  },
  "zh-CN": {
    title: "清单",
    close: "关闭",
    back: "返回",
    newList: "新清单",
    namePlaceholder: "名称，例如：购物",
    untitled: "未命名清单",
    empty: "还没有清单",
    progress: "已完成 {done}/{total}",
    shared: "已共享",
    delete: "删除",
    confirmDelete: "要从这台手机删除“{name}”吗？对方会保留自己的副本。",
    cancel: "取消",
    rename: "重命名",
    save: "保存",
    addPlaceholder: "添加一项",
    add: "添加",
    edit: "编辑",
    remove: "移除",
    send: "把清单放进聊天",
    live: "实时",
    stopLive: "停止实时",
    waiting: "🔄 正在等待对方…",
    joined: "🔄 实时：你们都在这个清单里",
    silent: "👤 对方没有在这个对话中打开 {app}。对方可能没有安装、没有授权，或已经关闭。",
    unreachable: "📵 现在无法连接到对方的手机。",
    left: "👋 对方关闭了清单。",
    outdated: "📦 对方的 {app} 版本更新。请更新 {app} 以便一起编辑。",
    kept: "你的更改会保留在这台手机上，等你们俩都在这个对话中打开清单时再与对方的合并。",
    liveHint: "🔄 只有你们俩都在这个对话中打开这个清单时，实时模式才会合并更改。",
    needsChat: "要一起编辑，请从对话中打开 {app}，并允许实时功能。",
    localHint: "在这里创建的清单只保留在这台手机上。对话中的清单只能在该对话中看到。",
    joinPrompt: "📥 对方打开了“{name}”",
    join: "加入",
    notNow: "以后再说",
    received: "共享清单",
    full: "📵 这台手机没有空间了：最近的更改没有保存。删除一个清单以腾出空间。",
    readOnly: "📦 这个清单来自更新版本的 {app}：请更新后再编辑。",
  },
  "zh-TW": {
    title: "清單",
    close: "關閉",
    back: "返回",
    newList: "新清單",
    namePlaceholder: "名稱，例如：購物",
    untitled: "未命名清單",
    empty: "還沒有清單",
    progress: "已完成 {done}/{total}",
    shared: "已共享",
    delete: "刪除",
    confirmDelete: "要從這支手機刪除「{name}」嗎？對方會保留自己的副本。",
    cancel: "取消",
    rename: "重新命名",
    save: "儲存",
    addPlaceholder: "新增一項",
    add: "新增",
    edit: "編輯",
    remove: "移除",
    send: "把清單放進聊天",
    live: "即時",
    stopLive: "停止即時",
    waiting: "🔄 正在等待對方…",
    joined: "🔄 即時：你們都在這個清單裡",
    silent: "👤 對方沒有在這個對話中開啟 {app}。對方可能沒有安裝、沒有授權，或已經關閉。",
    unreachable: "📵 現在無法連線到對方的手機。",
    left: "👋 對方關閉了清單。",
    outdated: "📦 對方的 {app} 版本較新。請更新 {app} 以便一起編輯。",
    kept: "你的變更會保留在這支手機上，等你們都在這個對話中開啟清單時再與對方的合併。",
    liveHint: "🔄 只有你們都在這個對話中開啟這個清單時，即時模式才會合併變更。",
    needsChat: "要一起編輯，請從對話中開啟 {app}，並允許即時功能。",
    localHint: "在這裡建立的清單只保留在這支手機上。對話中的清單只能在該對話中看到。",
    joinPrompt: "📥 對方開啟了「{name}」",
    join: "加入",
    notNow: "稍後再說",
    received: "共享清單",
    full: "📵 這支手機沒有空間了：最近的變更沒有儲存。刪除一個清單以騰出空間。",
    readOnly: "📦 這個清單來自較新版本的 {app}：請更新後再編輯。",
  },
};
